[project]
name = "ibm-ai-engineering-professional"
version = "0.1.0"
description = ""
authors = [
    {name = "ngoc",email = "ngochust56@gmail.com"}
]
readme = "README.md"
package-mode = false

requires-python = ">=3.12"

dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "matplotlib (>=3.10.0,<4.0.0)",
    "scikit-learn (>=1.6.0,<2.0.0)",
    "tensorflow (>=2.18.0,<3.0.0)",
    "numpy (==2.0.2)",
    "torch (>=2.5.1,<3.0.0)",
    "torchvision (>=0.20.1,<0.21.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
